// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type LogTest struct {
	ID       	int64	`gorm:"primary_key"`
	Ivalue   	int32	`gorm:"ivalue"`
	Svalue   	string	`gorm:"svalue"`
	Tvalue   	string	`gorm:"tvalue"`
	BlobValue	[]byte	`gorm:"blob_value"`
	Ivalue2  	int64	`gorm:"ivalue2"`
	OptType  	int32	`gorm:"opt_type"`
}
func (t *LogTest) TableName() string {
	return "log_test"
}