// --- this file generated by tools, please write your code in custom block ---
package tbobj

import (
	"helpertools/pkg/ormdef"
	"helpertools/pkg/pborm"
)

type TbLogTest struct{
	TableObjOpt
	ormMeta *ormdef.LogTest
	// ------------------ customtag1 code begin ---------------------
	// xxx code
	// ------------------ customtag1 code end -----------------------
}

// ID
func (tb *TbLogTest) GetID() int64 {
	return tb.ormMeta.ID
}
func (tb *TbLogTest) SetID(id int64) {
	tb.ormMeta.ID = id
	tb.SetDbStatus(DbStatusUpdate)
}

// Ivalue
func (tb *TbLogTest) GetIvalue() int32 {
	return tb.ormMeta.Ivalue
}
func (tb *TbLogTest) SetIvalue(ivalue int32) {
	tb.ormMeta.Ivalue = ivalue
	tb.SetDbStatus(DbStatusUpdate)
}

// Svalue
func (tb *TbLogTest) GetSvalue() string {
	return tb.ormMeta.Svalue
}
func (tb *TbLogTest) SetSvalue(svalue string) {
	tb.ormMeta.Svalue = svalue
	tb.SetDbStatus(DbStatusUpdate)
}

// Tvalue
func (tb *TbLogTest) GetTvalue() string {
	return tb.ormMeta.Tvalue
}
func (tb *TbLogTest) SetTvalue(tvalue string) {
	tb.ormMeta.Tvalue = tvalue
	tb.SetDbStatus(DbStatusUpdate)
}

// BlobValue
func (tb *TbLogTest) GetBlobValue() []byte {
	return tb.ormMeta.BlobValue
}
func (tb *TbLogTest) SetBlobValue(blobValue []byte) {
	tb.ormMeta.BlobValue = blobValue
	tb.SetDbStatus(DbStatusUpdate)
}

// Ivalue2
func (tb *TbLogTest) GetIvalue2() int64 {
	return tb.ormMeta.Ivalue2
}
func (tb *TbLogTest) SetIvalue2(ivalue2 int64) {
	tb.ormMeta.Ivalue2 = ivalue2
	tb.SetDbStatus(DbStatusUpdate)
}

// OptType
func (tb *TbLogTest) GetOptType() int32 {
	return tb.ormMeta.OptType
}
func (tb *TbLogTest) SetOptType(optType int32) {
	tb.ormMeta.OptType = optType
	tb.SetDbStatus(DbStatusUpdate)
}

func (tb *TbLogTest) DumpToPbOrm() *pborm.LogTest {
	tb.Serialize()
	pbObj := &pborm.LogTest{
		ID: tb.ormMeta.ID,
		Ivalue: tb.ormMeta.Ivalue,
		Svalue: tb.ormMeta.Svalue,
		Tvalue: tb.ormMeta.Tvalue,
		BlobValue: tb.ormMeta.BlobValue,
		Ivalue2: tb.ormMeta.Ivalue2,
		OptType: tb.ormMeta.OptType,
	}
	pbObj.BlobValue = make([]byte, len(tb.ormMeta.BlobValue))
	copy(pbObj.BlobValue, tb.ormMeta.BlobValue)
	pbObj.DbStatus = int32(tb.dbStatus)
	return pbObj
}
func (tb *TbLogTest) LoadFromPbOrm(obj *pborm.LogTest) {
	tb.ormMeta.ID = obj.ID
	tb.ormMeta.Ivalue = obj.Ivalue
	tb.ormMeta.Svalue = obj.Svalue
	tb.ormMeta.Tvalue = obj.Tvalue
	tb.ormMeta.BlobValue = obj.BlobValue
	tb.ormMeta.Ivalue2 = obj.Ivalue2
	tb.ormMeta.OptType = obj.OptType
	tb.ormMeta.BlobValue = make([]byte, len(obj.BlobValue))
	copy(tb.ormMeta.BlobValue, obj.BlobValue)
	tb.dbStatus = int8(obj.DbStatus)
	tb.Unserialize()
}
func NewTbLogTest() *TbLogTest {
	return &TbLogTest{
		ormMeta: &ormdef.LogTest{
			ID: 0,
			Ivalue: 0,
			Svalue: "",
			Tvalue: "",
			BlobValue: make([]byte, 0),
			Ivalue2: 0,
			OptType: 0,
		},
	}
}
func (tb *TbLogTest) Serialize() {
	// ------------------ customtag2 code begin ---------------------
	// ------------------ customtag2 code end -----------------------
}
func (tb *TbLogTest) Unserialize() {
	// ------------------ customtag3 code begin ---------------------
	// ------------------ customtag3 code end -----------------------
}
